#!/bin/bash
# This script will set highest CPU priority to process by his name
# Usefull for games, etc

# Array of processes sorted by most important
PROC=\
(
	'League of Legends.exe' # Have to run priority in whole game. LoL menu has different proccess name
	'Wow.exe'
);


# Loop the array
for x in "${PROC[@]}"
do
	# Get PID from process name
	PID=`pidof "$x"`

	# Is process running?
	if [ -n "$PID" ]; then
		# Print process name
		echo $x

		# Set priority and end loop
		taskset -p 1 $PID
		exit
	fi
done

echo "No running proccesses from \$PROC"
